on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Build Javadocs
        run: javadoc -public -d "docs" -sourcepath "src" -subpackages commands game items rooms ui

      - name: Push changes to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update javadocs
